public enum ChallengeMyTowerState{
  PLACING_TOWER, TOO_MANY_FIRST, TOO_SHORT, ENOUGH,ENOUGH_DELAY, SHAKING, PLACING_TOWER_SHAKING, TOO_MANY_SHAKING, TOO_SHORT_SHAKING, RESULT, FAIL, SUCCESS, RESET;
}
